#!/usr/bin/env bash

# Hooks are sourced, so we need to set flags via `set`, not shebang.
set -eu

# See https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/
#
# > Treeless clones are really only helpful for automated
# > builds when you want to quickly clone, compile a project,
# > then throw away the repository. In environments like
# > GitHub Actions using public runners, you want to minimize
# > your clone time so you can spend your machine time
# > actually building your software! Treeless clones might be
# > an excellent option for those environments.

export BUILDKITE_GIT_CLONE_FLAGS="--filter=tree:0 --recurse-submodules --also-filter-submodules"

# See failure message in
# https://buildkite.com/automattic/gutenberg-mobile/builds/8768#018e16eb-c55e-4d98-84dc-464ef03dafc4/190-210
git config submodule.alternateErrorStrategy info
